import type { Locale } from "@/lib/i18n";
import { translateValue } from "@/lib/translate";

export type FaultCode = {
  code: string;
  title: string;
  system: string;
  severity: "Low" | "Medium" | "High";
  summary: string;
  symptoms: string[];
  likelyCauses: string[];
  firstChecks: string[];
  warning: string;
  keywords: string[];
};

export const faultCodes: FaultCode[] = [
  {
    code: "P0016",
    title: "Crankshaft / camshaft timing correlation",
    system: "Engine timing",
    severity: "High",
    summary: "The ECU sees the crankshaft and camshaft signals outside their expected relationship.",
    symptoms: ["Long cranking", "Rough running", "Reduced power", "Cold-start rattle"],
    likelyCauses: ["Stretched or incorrectly installed timing drive", "Cam or crank sensor signal fault", "Oil-pressure or variable-timing control issue"],
    firstChecks: ["Confirm oil level and correct oil specification", "Read freeze-frame and manufacturer-specific timing values", "Inspect timing mechanically before replacing sensors"],
    warning: "Continued driving can risk internal engine damage when mechanical timing is genuinely incorrect.",
    keywords: ["timing chain", "camshaft", "crankshaft", "cold start"],
  },
  {
    code: "P0087",
    title: "Fuel rail pressure too low",
    system: "Fuel delivery",
    severity: "High",
    summary: "Measured fuel pressure fell below the pressure requested by the engine controller.",
    symptoms: ["Hard starting", "Hesitation", "Stalling", "Reduced-power mode"],
    likelyCauses: ["Restricted fuel supply", "Weak low- or high-pressure pump", "Injector leak-off", "Pressure sensor or control-valve fault"],
    firstChecks: ["Compare requested and actual pressure", "Check filter and low-pressure supply", "Perform injector return-flow testing where applicable"],
    warning: "High-pressure fuel systems require correct equipment and safe workshop procedures.",
    keywords: ["fuel pressure", "rail pressure", "injector", "pump"],
  },
  {
    code: "P0101",
    title: "Mass-air-flow signal range / performance",
    system: "Air metering",
    severity: "Medium",
    summary: "Airflow reported by the MAF sensor does not agree with the ECU's calculated operating conditions.",
    symptoms: ["Poor response", "Smoke", "Uneven idle", "Fuel-economy change"],
    likelyCauses: ["Air leak after the sensor", "Contaminated or failed MAF", "EGR flow problem", "Boost or intake restriction"],
    firstChecks: ["Inspect intake hoses and clamps", "Compare MAF data with expected values", "Check EGR and boost plausibility before replacing the sensor"],
    warning: "A MAF code often describes a system plausibility problem, not automatically a failed MAF sensor.",
    keywords: ["MAF", "air flow", "intake leak", "EGR"],
  },
  {
    code: "P0171",
    title: "System too lean, bank 1",
    system: "Fuel mixture",
    severity: "Medium",
    summary: "Fuel trim has reached a lean threshold because the ECU is adding more fuel than expected.",
    symptoms: ["Rough idle", "Hesitation", "Whistling noise", "Misfires"],
    likelyCauses: ["Vacuum or PCV leak", "Low fuel pressure", "Incorrect airflow reading", "Exhaust leak before the oxygen sensor"],
    firstChecks: ["Review short- and long-term fuel trims", "Smoke-test the intake", "Check PCV operation and fuel pressure"],
    warning: "Use trim behavior at idle and under load to separate air leaks from fuel-delivery faults.",
    keywords: ["lean", "fuel trim", "vacuum leak", "PCV"],
  },
  {
    code: "P0234",
    title: "Turbocharger overboost condition",
    system: "Turbocharging",
    severity: "High",
    summary: "Boost pressure exceeded the ECU's permitted target for the operating condition.",
    symptoms: ["Reduced-power mode", "Abrupt power loss", "Boost surge", "Engine warning light"],
    likelyCauses: ["Sticking turbo vanes or wastegate", "Faulty boost-control valve", "Restricted vacuum control", "Incorrect pressure signal"],
    firstChecks: ["Compare requested and actual boost", "Inspect vacuum lines and actuator travel", "Check charge-pressure sensor plausibility"],
    warning: "Do not continue repeated full-load testing until boost control is understood.",
    keywords: ["overboost", "turbo", "wastegate", "boost control"],
  },
  {
    code: "P0299",
    title: "Turbocharger underboost condition",
    system: "Turbocharging",
    severity: "Medium",
    summary: "The engine did not produce the boost pressure requested by the controller.",
    symptoms: ["Low power", "Hissing under load", "Smoke", "Reduced-power mode"],
    likelyCauses: ["Split charge hose or intercooler leak", "Actuator or vacuum fault", "Worn turbocharger", "EGR or exhaust restriction"],
    firstChecks: ["Pressure- or smoke-test the charge system", "Log requested versus actual boost", "Check actuator command and movement"],
    warning: "Confirm leaks and control faults before condemning the turbocharger.",
    keywords: ["underboost", "turbo", "charge hose", "intercooler"],
  },
  {
    code: "P0300",
    title: "Random / multiple-cylinder misfire",
    system: "Combustion",
    severity: "High",
    summary: "Misfires are occurring across more than one cylinder or without one consistent cylinder pattern.",
    symptoms: ["Shaking idle", "Flashing warning light", "Poor acceleration", "Fuel smell"],
    likelyCauses: ["Ignition faults", "Air or fuel imbalance", "Injector problems", "Mechanical compression issue"],
    firstChecks: ["Stop heavy driving if the warning lamp flashes", "Read cylinder-specific counters", "Check plugs, coils, trims, injectors, and compression logically"],
    warning: "Active misfire can overheat and damage the catalytic converter.",
    keywords: ["misfire", "coil", "spark plug", "injector"],
  },
  {
    code: "P0401",
    title: "Exhaust-gas recirculation flow insufficient",
    system: "EGR",
    severity: "Medium",
    summary: "Measured or inferred EGR flow is lower than the controller expects.",
    symptoms: ["Engine warning light", "Reduced power", "Knock or harsh combustion", "Emissions fault"],
    likelyCauses: ["Carbon-blocked EGR passages", "Sticking EGR valve", "Sensor plausibility fault", "Vacuum or actuator problem"],
    firstChecks: ["Command the EGR while monitoring airflow", "Inspect passages and cooler for restriction", "Verify pressure and temperature sensors"],
    warning: "Cleaning only the valve may not fix blocked passages or a failed control system.",
    keywords: ["EGR", "carbon", "emissions", "air flow"],
  },
  {
    code: "P0420",
    title: "Catalyst efficiency below threshold, bank 1",
    system: "Emissions",
    severity: "Medium",
    summary: "Upstream and downstream oxygen-sensor behavior suggests insufficient catalyst oxygen-storage performance.",
    symptoms: ["Engine warning light", "Possible sulfur smell", "Usually little drivability change"],
    likelyCauses: ["Aged or damaged catalyst", "Long-term misfire or mixture fault", "Exhaust leak", "Biased oxygen sensor"],
    firstChecks: ["Repair mixture and misfire faults first", "Check for exhaust leaks", "Review live upstream/downstream sensor behavior"],
    warning: "Replacing the catalyst without correcting the cause can lead to another failure.",
    keywords: ["catalyst", "oxygen sensor", "emissions", "exhaust"],
  },
  {
    code: "P2002",
    title: "Diesel particulate filter efficiency below threshold",
    system: "DPF",
    severity: "High",
    summary: "The ECU calculates that particulate-filter performance is below its required threshold.",
    symptoms: ["DPF warning", "Frequent regeneration", "Reduced power", "Higher fuel use"],
    likelyCauses: ["Ash-loaded or damaged DPF", "Differential-pressure sensor fault", "Exhaust leak", "Underlying soot-production problem"],
    firstChecks: ["Read soot and ash estimates", "Check pressure values with engine off and under load", "Inspect temperature sensors and regeneration history"],
    warning: "Forced regeneration is unsafe when loading, oil level, or temperature-sensor data is not understood.",
    keywords: ["DPF", "diesel", "soot", "regeneration"],
  },
  {
    code: "P2015",
    title: "Intake-manifold runner position range / performance",
    system: "Intake control",
    severity: "Medium",
    summary: "The intake-runner position signal is outside the range expected by the controller.",
    symptoms: ["Warning light", "Flat low-speed response", "Uneven running", "Occasional reduced power"],
    likelyCauses: ["Worn linkage or stop", "Carbon-restricted swirl flaps", "Actuator fault", "Position-sensor fault"],
    firstChecks: ["Inspect linkage movement", "Run actuator output tests", "Check for carbon restriction and wiring faults"],
    warning: "The correct repair depends heavily on the exact engine and manifold design.",
    keywords: ["intake runner", "swirl flap", "manifold", "actuator"],
  },
  {
    code: "P20EE",
    title: "SCR NOx catalyst efficiency below threshold",
    system: "AdBlue / SCR",
    severity: "High",
    summary: "The SCR system is not reducing NOx emissions as effectively as the ECU expects.",
    symptoms: ["AdBlue warning", "Engine light", "Possible restart countdown", "No obvious drivability symptom"],
    likelyCauses: ["Biased NOx sensor", "Incorrect AdBlue dosing", "Poor fluid quality", "Exhaust leak or aged SCR catalyst"],
    firstChecks: ["Read upstream and downstream NOx values", "Verify dosing and fluid quality", "Check temperature data and related faults"],
    warning: "Parts substitution is expensive; diagnose the complete SCR system before replacement.",
    keywords: ["SCR", "AdBlue", "NOx", "diesel emissions"],
  },
  {
    code: "P204F",
    title: "Reductant system performance",
    system: "AdBlue / SCR",
    severity: "High",
    summary: "The reductant system is not meeting the performance expected by the emissions controller.",
    symptoms: ["AdBlue warning", "Restart countdown", "Engine light", "Emissions readiness failure"],
    likelyCauses: ["AdBlue pump or pressure fault", "Dosing injector problem", "NOx sensor issue", "Incorrect fluid or tank heater fault"],
    firstChecks: ["Scan SCR subcodes and freeze-frame", "Check reductant pressure and dosing command", "Verify fluid quality and NOx sensor data"],
    warning: "A generic P204F should be diagnosed with manufacturer data before replacing the tank or sensors.",
    keywords: ["AdBlue", "SCR", "reductant", "NOx"],
  },
  {
    code: "P2201",
    title: "NOx sensor circuit range / performance",
    system: "NOx sensing",
    severity: "High",
    summary: "A NOx sensor signal or its controller behavior is outside the expected operating range.",
    symptoms: ["Engine or AdBlue warning", "Restart countdown on some vehicles", "Emissions-system messages"],
    likelyCauses: ["Failed NOx sensor or control module", "Wiring or connector heat damage", "Exhaust leak", "Incorrect temperature or dosing behavior"],
    firstChecks: ["Identify the exact sensor position", "Inspect wiring near the exhaust", "Compare sensor values after correct warm-up"],
    warning: "Manufacturer-specific subcodes are essential because several NOx sensors may be fitted.",
    keywords: ["NOx sensor", "AdBlue", "SCR", "wiring"],
  },
  {
    code: "P2453",
    title: "DPF differential-pressure sensor range / performance",
    system: "DPF sensing",
    severity: "Medium",
    summary: "The pressure signal used to calculate DPF restriction is implausible or outside range.",
    symptoms: ["DPF warning", "Regeneration problems", "Reduced power", "Incorrect soot estimate"],
    likelyCauses: ["Blocked, split, or reversed pressure hoses", "Failed pressure sensor", "Wiring fault", "Severely restricted filter"],
    firstChecks: ["Check key-on engine-off pressure value", "Inspect both pressure hoses", "Compare pressure at idle and raised speed"],
    warning: "A bad pressure signal can mislead regeneration strategy and soot-load calculations.",
    keywords: ["DPF pressure", "sensor", "hose", "regeneration"],
  },
  {
    code: "P2458",
    title: "DPF regeneration duration",
    system: "DPF",
    severity: "High",
    summary: "A diesel particulate filter regeneration took too long or did not complete as expected.",
    symptoms: ["DPF warning", "Cooling fans running often", "Reduced power", "Fuel economy drop"],
    likelyCauses: ["Short-trip driving", "Thermostat not reaching temperature", "DPF pressure sensor fault", "Excess soot from EGR, injector, or boost issues"],
    firstChecks: ["Check coolant temperature and thermostat behavior", "Read soot load and pressure values", "Review regeneration history and driving pattern"],
    warning: "Repeated incomplete regeneration can dilute oil and push the DPF into a high-risk soot load.",
    keywords: ["DPF regeneration", "soot", "diesel", "thermostat"],
  },
  {
    code: "P2463",
    title: "Diesel particulate filter soot accumulation",
    system: "DPF",
    severity: "High",
    summary: "Calculated soot loading has reached a level that requires diagnosis before normal operation can continue.",
    symptoms: ["Reduced power", "DPF warning", "Regeneration inhibited", "Cooling fans running"],
    likelyCauses: ["Repeated interrupted regeneration", "Thermostat or sensor fault", "EGR/injector/boost issue increasing soot", "Restricted or ash-loaded DPF"],
    firstChecks: ["Check calculated soot and ash load", "Find why regeneration failed", "Inspect oil level before any regeneration procedure"],
    warning: "Do not force regeneration solely from the code; excessive loading can create a fire or turbo risk.",
    keywords: ["DPF blocked", "soot", "regeneration", "diesel"],
  },
  {
    code: "U0100",
    title: "Lost communication with engine control module",
    system: "Vehicle network",
    severity: "High",
    summary: "One or more modules stopped receiving expected messages from the engine controller.",
    symptoms: ["No start", "Multiple warning lights", "Intermittent shutdown", "Many network codes"],
    likelyCauses: ["Low system voltage", "Power or ground loss at the ECU", "CAN wiring fault", "Module or gateway issue"],
    firstChecks: ["Test battery voltage and charging health", "Check ECU powers and grounds", "Map which modules can and cannot communicate"],
    warning: "A network code does not by itself prove that the engine ECU has failed.",
    keywords: ["CAN bus", "communication", "ECU", "battery"],
  },
  {
    code: "P0113",
    title: "Intake-air temperature sensor circuit high",
    system: "Air metering",
    severity: "Medium",
    summary: "The ECU sees an intake-air temperature signal that is higher voltage than expected, often interpreted as an unrealistically cold reading.",
    symptoms: ["Engine warning light", "Poor cold running", "Rich mixture", "Reduced economy"],
    likelyCauses: ["Disconnected IAT sensor", "Open circuit in the signal wire", "Sensor contamination or failure", "MAF/IAT combined sensor fault"],
    firstChecks: ["Compare intake-air temperature to ambient before starting", "Inspect the MAF/IAT connector and wiring", "Check for a plausible signal while moving the harness"],
    warning: "Do not replace the sensor until the live temperature value and connector condition have been checked.",
    keywords: ["IAT", "intake temperature", "MAF", "air sensor"],
  },
  {
    code: "P0128",
    title: "Coolant thermostat below regulating temperature",
    system: "Cooling system",
    severity: "Medium",
    summary: "The engine is taking too long to reach expected operating temperature or is running cooler than the ECU expects.",
    symptoms: ["Poor heater output", "High fuel use", "Temperature gauge low", "Emissions readiness issues"],
    likelyCauses: ["Thermostat stuck open", "Coolant-temperature sensor bias", "Low coolant level", "Incorrect thermostat or previous repair issue"],
    firstChecks: ["Log coolant temperature from cold", "Compare sensor data with actual hose temperature", "Inspect coolant level and thermostat history"],
    warning: "A cold-running engine can increase fuel use, soot production, and DPF regeneration trouble on diesels.",
    keywords: ["thermostat", "coolant temperature", "warm-up", "heater"],
  },
  {
    code: "P0130",
    title: "Oxygen sensor circuit malfunction, bank 1 sensor 1",
    system: "Oxygen sensing",
    severity: "Medium",
    summary: "The upstream oxygen or lambda sensor signal is implausible, missing, or outside the control range expected by the ECU.",
    symptoms: ["Engine warning light", "Poor fuel economy", "Rough idle", "Failed emissions test"],
    likelyCauses: ["Failed upstream oxygen sensor", "Wiring or connector damage", "Exhaust leak before the sensor", "Mixture fault pushing the sensor out of range"],
    firstChecks: ["Review fuel trims and sensor switching behavior", "Inspect wiring near heat shields and exhaust", "Check for exhaust leaks before replacing parts"],
    warning: "A lambda code can be caused by mixture or exhaust faults, not only the sensor itself.",
    keywords: ["oxygen sensor", "lambda", "fuel trim", "exhaust leak"],
  },
  {
    code: "P0172",
    title: "System too rich, bank 1",
    system: "Fuel mixture",
    severity: "Medium",
    summary: "Fuel trim has reached a rich threshold because the ECU is removing more fuel than expected.",
    symptoms: ["Fuel smell", "Poor economy", "Sooty tailpipe", "Rough idle"],
    likelyCauses: ["Leaking injector", "Incorrect airflow reading", "High fuel pressure", "Failed purge valve or rich EVAP flow"],
    firstChecks: ["Review short- and long-term fuel trims", "Check fuel pressure and injector leak-down", "Inspect purge valve operation and MAF plausibility"],
    warning: "Driving with a rich mixture can damage catalysts and dilute engine oil.",
    keywords: ["rich", "fuel trim", "injector", "MAF"],
  },
  {
    code: "P0442",
    title: "EVAP system small leak detected",
    system: "EVAP",
    severity: "Low",
    summary: "The fuel-vapor system cannot hold the small vacuum or pressure change expected during the leak test.",
    symptoms: ["Engine warning light", "Fuel smell", "Usually no drivability symptom"],
    likelyCauses: ["Loose or damaged fuel cap", "Small cracked EVAP hose", "Purge or vent valve leak", "Charcoal canister or seal issue"],
    firstChecks: ["Inspect the fuel cap and seal", "Smoke-test the EVAP system", "Command purge and vent valves while monitoring sealing behavior"],
    warning: "Small EVAP leaks are often simple, but guessing parts can get expensive quickly.",
    keywords: ["EVAP leak", "fuel cap", "purge valve", "smoke test"],
  },
  {
    code: "P0507",
    title: "Idle control system RPM higher than expected",
    system: "Idle control",
    severity: "Medium",
    summary: "Idle speed is higher than the ECU's target after it has reached the limit of normal control correction.",
    symptoms: ["High idle", "Surging idle", "Harsh gear engagement", "Whistling air leak"],
    likelyCauses: ["Vacuum or PCV leak", "Dirty throttle body", "Incorrect throttle adaptation", "Stuck idle-control or purge flow issue"],
    firstChecks: ["Smoke-test intake and PCV paths", "Review throttle angle and fuel trims", "Perform throttle adaptation only after fixing air leaks"],
    warning: "High idle is often an air-management problem, not automatically a throttle-body failure.",
    keywords: ["high idle", "vacuum leak", "PCV", "throttle body"],
  },
  {
    code: "P0700",
    title: "Transmission control system requested warning",
    system: "Transmission",
    severity: "High",
    summary: "The engine controller has been told by the transmission controller that a gearbox-related fault is present.",
    symptoms: ["Gearbox warning", "Limp mode", "Harsh shifts", "Limited gear selection"],
    likelyCauses: ["Stored transmission controller fault", "Low voltage", "Fluid or pressure issue", "Mechatronics, solenoid, or sensor fault"],
    firstChecks: ["Scan the transmission controller directly", "Check battery and charging voltage", "Review fluid service history and exact gearbox codes"],
    warning: "P0700 is a pointer code; the real diagnosis is in the transmission module's manufacturer-specific faults.",
    keywords: ["transmission", "gearbox", "TCM", "limp mode"],
  },
  {
    code: "P0730",
    title: "Incorrect gear ratio",
    system: "Transmission",
    severity: "High",
    summary: "The gearbox input and output speeds do not match the gear ratio the controller expected.",
    symptoms: ["Flare between gears", "Harsh shifts", "Limp mode", "Delayed engagement"],
    likelyCauses: ["Low or degraded transmission fluid", "Internal clutch slip", "Mechatronics or solenoid fault", "Speed-sensor or adaptation issue"],
    firstChecks: ["Scan gearbox data and ratio errors", "Check fluid level and service history using the correct procedure", "Assess shift behavior cold and hot"],
    warning: "Continued driving with actual clutch slip can turn a repairable issue into a gearbox rebuild.",
    keywords: ["incorrect gear ratio", "gearbox slip", "mechatronics", "transmission fluid"],
  },
  {
    code: "P2187",
    title: "System too lean at idle, bank 1",
    system: "Fuel mixture",
    severity: "Medium",
    summary: "The ECU detects a lean condition mainly at idle, where small air leaks have a larger effect on mixture control.",
    symptoms: ["Rough idle", "Stalling", "Whistling noise", "Hesitation leaving idle"],
    likelyCauses: ["PCV diaphragm leak", "Vacuum hose leak", "Intake manifold leak", "Purge valve stuck open"],
    firstChecks: ["Compare fuel trims at idle and raised RPM", "Smoke-test the intake and PCV system", "Check purge valve sealing"],
    warning: "Idle-only lean faults are usually diagnosed faster with smoke testing than with parts swapping.",
    keywords: ["lean idle", "PCV", "vacuum leak", "purge valve"],
  },
  {
    code: "C1130",
    title: "Chassis control or suspension pressure fault",
    system: "Chassis / suspension",
    severity: "Medium",
    summary: "A chassis or suspension control module has detected an implausible pressure, height, or control-state condition.",
    symptoms: ["Suspension warning", "Vehicle sits low", "Compressor runs often", "Uneven ride height"],
    likelyCauses: ["Air spring leak", "Compressor weakness", "Height sensor fault", "Valve block or wiring issue"],
    firstChecks: ["Scan the chassis module with brand-capable diagnostics", "Check ride height after the car sits overnight", "Inspect air lines, bags, compressor run time, and voltage"],
    warning: "Manufacturer-specific subcodes are essential because C-codes vary more by brand than generic engine codes.",
    keywords: ["air suspension", "Airmatic", "chassis", "ride height"],
  },
  {
    code: "U0121",
    title: "Lost communication with ABS control module",
    system: "Vehicle network",
    severity: "High",
    summary: "Modules on the vehicle network are not receiving expected messages from the ABS or stability-control controller.",
    symptoms: ["ABS warning", "Stability-control warning", "Speedometer issues", "Multiple network codes"],
    likelyCauses: ["Low battery voltage", "ABS module power or ground fault", "CAN wiring issue", "Water ingress or module failure"],
    firstChecks: ["Test battery and charging health", "Check ABS module powers, grounds, and fuses", "Inspect wheel-arch and module-area wiring for damage or water"],
    warning: "ABS communication faults can affect braking assistance and stability functions, so diagnose before normal use.",
    keywords: ["ABS", "CAN bus", "stability control", "communication"],
  },
  {
    code: "P0011",
    title: "Intake camshaft timing over-advanced, bank 1",
    system: "Variable valve timing",
    severity: "High",
    summary: "The intake camshaft is more advanced than the ECU expects for the current operating condition.",
    symptoms: ["Rough idle", "Poor response", "Cold-start rattle", "Engine warning light"],
    likelyCauses: ["Incorrect or dirty oil", "Sticking camshaft adjuster solenoid", "Timing-chain stretch", "Camshaft actuator or oil-control fault"],
    firstChecks: ["Confirm oil level and correct specification", "Check live camshaft adaptation values", "Inspect timing and oil-control solenoid operation before replacing parts"],
    warning: "Cam timing faults can be oil-control issues or real mechanical timing problems; do not ignore repeated faults.",
    keywords: ["cam timing", "VVT", "timing chain", "oil control"],
  },
  {
    code: "P0014",
    title: "Exhaust camshaft timing over-advanced, bank 1",
    system: "Variable valve timing",
    severity: "High",
    summary: "The exhaust camshaft position is more advanced than commanded or is slow to return to the expected position.",
    symptoms: ["Uneven idle", "Poor acceleration", "Rattle on startup", "Engine warning light"],
    likelyCauses: ["Sticking exhaust cam actuator", "Dirty oil or blocked oil passage", "Timing-chain wear", "Camshaft position sensor plausibility issue"],
    firstChecks: ["Check oil condition and service history", "Compare commanded versus actual cam angle", "Inspect solenoid screens and timing data"],
    warning: "Repeated cam timing faults deserve diagnosis before long drives or hard acceleration.",
    keywords: ["exhaust cam", "VVT", "timing", "camshaft actuator"],
  },
  {
    code: "P0102",
    title: "Mass-air-flow circuit low input",
    system: "Air metering",
    severity: "Medium",
    summary: "The MAF sensor signal is lower than expected for the engine speed and load.",
    symptoms: ["Low power", "Rough idle", "Poor fuel economy", "Smoke on acceleration"],
    likelyCauses: ["Disconnected or failed MAF sensor", "Wiring or ground fault", "Intake restriction", "Air leak or incorrect sensor reading"],
    firstChecks: ["Inspect the MAF connector and intake tract", "Compare MAF grams-per-second with expected values", "Check power, ground, and signal wiring"],
    warning: "A low MAF signal can come from wiring, airflow restriction, or air leaks, not only the sensor.",
    keywords: ["MAF low", "airflow", "intake", "wiring"],
  },
  {
    code: "P0118",
    title: "Engine coolant temperature sensor circuit high",
    system: "Cooling system",
    severity: "Medium",
    summary: "The coolant-temperature signal is implausibly high voltage, often read by the ECU as extremely cold coolant.",
    symptoms: ["Hard starting", "Rich running", "Cooling fan behavior changes", "Temperature reading implausible"],
    likelyCauses: ["Open circuit in coolant sensor wiring", "Failed coolant temperature sensor", "Connector corrosion", "Incorrect sensor data after repair"],
    firstChecks: ["Compare coolant temperature to ambient before startup", "Inspect the sensor connector and wiring", "Check live data while moving the harness"],
    warning: "Bad temperature data can affect fueling, fan control, warm-up strategy, and emissions readiness.",
    keywords: ["coolant sensor", "temperature", "ECT", "warm-up"],
  },
  {
    code: "P0135",
    title: "Oxygen sensor heater circuit, bank 1 sensor 1",
    system: "Oxygen sensing",
    severity: "Medium",
    summary: "The upstream oxygen sensor heater circuit is not operating as expected.",
    symptoms: ["Engine warning light", "Poor cold-start emissions", "Delayed closed-loop fueling", "Fuel economy change"],
    likelyCauses: ["Failed oxygen sensor heater", "Blown fuse", "Wiring near exhaust damaged", "ECU heater-control fault"],
    firstChecks: ["Check heater fuse and power supply", "Inspect wiring close to the exhaust", "Measure heater resistance and command behavior"],
    warning: "Heater faults can be wiring or fuse issues; do not assume the sensor is the only failed part.",
    keywords: ["oxygen sensor heater", "lambda", "heater circuit", "emissions"],
  },
  {
    code: "P0141",
    title: "Oxygen sensor heater circuit, bank 1 sensor 2",
    system: "Oxygen sensing",
    severity: "Medium",
    summary: "The downstream oxygen sensor heater circuit is not reaching expected operation.",
    symptoms: ["Engine warning light", "Catalyst monitor not ready", "Usually little drivability change"],
    likelyCauses: ["Failed downstream oxygen sensor heater", "Damaged exhaust-area wiring", "Fuse or relay issue", "Connector corrosion"],
    firstChecks: ["Inspect sensor wiring and connector", "Check heater power and ground", "Confirm catalyst-related codes are not the root cause"],
    warning: "A downstream heater fault can prevent emissions readiness even if the car drives normally.",
    keywords: ["downstream oxygen sensor", "heater", "catalyst monitor", "lambda"],
  },
  {
    code: "P0301",
    title: "Cylinder 1 misfire detected",
    system: "Combustion",
    severity: "High",
    summary: "The ECU detected repeated combustion misfires on cylinder 1.",
    symptoms: ["Shaking idle", "Flashing warning light", "Poor acceleration", "Fuel smell"],
    likelyCauses: ["Ignition coil or spark plug fault", "Injector problem", "Compression issue", "Air leak affecting one cylinder"],
    firstChecks: ["Avoid heavy driving if the warning light flashes", "Swap coil or plug only as a controlled test", "Check injector, compression, and leak-down if the fault stays on cylinder 1"],
    warning: "Active misfire can overheat and damage the catalytic converter.",
    keywords: ["cylinder 1", "misfire", "coil", "spark plug"],
  },
  {
    code: "P0302",
    title: "Cylinder 2 misfire detected",
    system: "Combustion",
    severity: "High",
    summary: "The ECU detected repeated combustion misfires on cylinder 2.",
    symptoms: ["Rough idle", "Flashing warning light", "Hesitation", "Unburned fuel smell"],
    likelyCauses: ["Ignition coil or spark plug fault", "Injector problem", "Compression issue", "Intake leak near cylinder 2"],
    firstChecks: ["Read misfire counters after a cold start and road test", "Swap ignition parts only to prove movement", "Check injector operation and mechanical compression"],
    warning: "Do not keep driving a flashing misfire light; catalyst damage can follow quickly.",
    keywords: ["cylinder 2", "misfire", "coil", "injector"],
  },
  {
    code: "P0303",
    title: "Cylinder 3 misfire detected",
    system: "Combustion",
    severity: "High",
    summary: "The ECU detected repeated combustion misfires on cylinder 3.",
    symptoms: ["Engine shake", "Poor acceleration", "Flashing warning light", "Rough cold start"],
    likelyCauses: ["Ignition component fault", "Injector flow problem", "Compression loss", "Carbon buildup affecting airflow"],
    firstChecks: ["Check cylinder-specific misfire data", "Inspect plugs and coils", "Confirm fuel and compression before replacing multiple parts"],
    warning: "A single-cylinder misfire that does not move with ignition parts needs deeper diagnosis.",
    keywords: ["cylinder 3", "misfire", "rough idle", "compression"],
  },
  {
    code: "P0304",
    title: "Cylinder 4 misfire detected",
    system: "Combustion",
    severity: "High",
    summary: "The ECU detected repeated combustion misfires on cylinder 4.",
    symptoms: ["Shaking idle", "Loss of power", "Flashing warning light", "Hard starting"],
    likelyCauses: ["Coil or plug failure", "Injector fault", "Vacuum or intake sealing issue", "Mechanical compression issue"],
    firstChecks: ["Review freeze-frame load and RPM", "Test ignition parts logically", "Check injector balance and compression if the fault remains"],
    warning: "Repeated cylinder-specific misfire should be fixed before catalyst or DPF damage follows.",
    keywords: ["cylinder 4", "misfire", "coil", "injector"],
  },
  {
    code: "P0325",
    title: "Knock sensor circuit malfunction",
    system: "Knock control",
    severity: "Medium",
    summary: "The ECU is not receiving a plausible signal from the knock sensor circuit.",
    symptoms: ["Reduced power", "Poor acceleration", "Engine warning light", "Possible pinging under load"],
    likelyCauses: ["Failed knock sensor", "Damaged wiring", "Incorrect torque or mounting issue", "Engine noise or poor fuel quality confusing knock control"],
    firstChecks: ["Inspect sensor wiring and connector", "Check for engine mechanical noise", "Verify fuel quality and sensor mounting before replacement"],
    warning: "Knock-control faults can make the ECU reduce power to protect the engine.",
    keywords: ["knock sensor", "detonation", "pinging", "reduced power"],
  },
  {
    code: "P0335",
    title: "Crankshaft position sensor circuit",
    system: "Engine speed sensing",
    severity: "High",
    summary: "The ECU is missing or cannot trust the crankshaft position signal.",
    symptoms: ["No start", "Stalling when hot", "Long cranking", "Tachometer drop"],
    likelyCauses: ["Failed crankshaft sensor", "Heat-related sensor fault", "Damaged wiring", "Reluctor wheel or signal gap issue"],
    firstChecks: ["Check RPM signal while cranking", "Inspect wiring near heat and moving parts", "Scope the crank signal if the fault is intermittent"],
    warning: "A failing crank sensor can cause sudden stalling or a no-start condition.",
    keywords: ["crank sensor", "no start", "stalling", "RPM signal"],
  },
  {
    code: "P0340",
    title: "Camshaft position sensor circuit, bank 1",
    system: "Camshaft sensing",
    severity: "Medium",
    summary: "The ECU is missing or cannot trust the camshaft position signal on bank 1.",
    symptoms: ["Long cranking", "Reduced power", "Rough running", "Engine warning light"],
    likelyCauses: ["Failed camshaft sensor", "Wiring or connector fault", "Timing correlation issue", "Oil contamination near sensor"],
    firstChecks: ["Compare cam and crank synchronization data", "Inspect connector and wiring", "Check for related timing faults before replacing the sensor"],
    warning: "Cam sensor codes can be caused by real timing problems, so check correlation data.",
    keywords: ["camshaft sensor", "long crank", "timing", "synchronization"],
  },
  {
    code: "P0411",
    title: "Secondary-air injection incorrect flow",
    system: "Secondary air",
    severity: "Medium",
    summary: "The ECU does not see the expected oxygen-sensor response when the secondary-air system runs on cold start.",
    symptoms: ["Engine warning light", "Noisy air pump", "Cold-start emissions fault", "Usually normal drivability"],
    likelyCauses: ["Failed secondary-air pump", "Blocked passages", "Stuck combi valve", "Vacuum or relay fault"],
    firstChecks: ["Confirm pump operation on cold start", "Check valve and vacuum control", "Inspect passages for carbon blockage"],
    warning: "The pump may be only one part of the system; blocked passages are common on older engines.",
    keywords: ["secondary air", "SAI", "cold start", "air pump"],
  },
  {
    code: "P0441",
    title: "EVAP purge flow incorrect",
    system: "EVAP",
    severity: "Low",
    summary: "The fuel-vapor purge system flow is not matching the ECU's commanded behavior.",
    symptoms: ["Engine warning light", "Hard start after refueling", "Fuel smell", "Rough idle after fill-up"],
    likelyCauses: ["Purge valve stuck open or closed", "Blocked EVAP line", "Charcoal canister issue", "Vacuum leak in purge plumbing"],
    firstChecks: ["Command the purge valve and monitor fuel trims", "Check valve sealing when off", "Inspect hoses and canister connections"],
    warning: "A purge valve stuck open can act like a vacuum leak and create mixture faults.",
    keywords: ["EVAP", "purge valve", "fuel smell", "hard start after refuel"],
  },
  {
    code: "P0455",
    title: "EVAP system gross leak detected",
    system: "EVAP",
    severity: "Low",
    summary: "The fuel-vapor system has a large leak or cannot seal during its self-test.",
    symptoms: ["Engine warning light", "Fuel smell", "Loose cap message", "Usually no drivability symptom"],
    likelyCauses: ["Loose or missing fuel cap", "Large cracked EVAP hose", "Vent valve stuck open", "Damaged charcoal canister"],
    firstChecks: ["Check fuel cap fit and seal", "Smoke-test the EVAP system", "Command vent and purge valves"],
    warning: "Large EVAP leaks are often simple, but the system should be smoke-tested rather than guessed.",
    keywords: ["EVAP gross leak", "fuel cap", "vent valve", "smoke test"],
  },
  {
    code: "P0456",
    title: "EVAP system very small leak detected",
    system: "EVAP",
    severity: "Low",
    summary: "The fuel-vapor system has a very small leak during the ECU's leak test.",
    symptoms: ["Engine warning light", "Usually no drivability symptom", "Occasional fuel smell"],
    likelyCauses: ["Fuel cap seal wear", "Tiny EVAP hose crack", "Purge or vent valve seepage", "Canister or filler-neck seal leak"],
    firstChecks: ["Inspect fuel cap and filler neck", "Smoke-test with correct EVAP equipment", "Check purge and vent valves for seepage"],
    warning: "Very small EVAP leaks are hard to find without smoke testing and patience.",
    keywords: ["EVAP small leak", "fuel cap", "P0456", "smoke test"],
  },
  {
    code: "P0562",
    title: "System voltage low",
    system: "Electrical power",
    severity: "High",
    summary: "System voltage fell below the level expected by the ECU during operation.",
    symptoms: ["Multiple warning lights", "Hard starting", "Module communication faults", "Random electrical behavior"],
    likelyCauses: ["Weak battery", "Charging-system fault", "Poor ground or terminal connection", "Voltage drop during cranking"],
    firstChecks: ["Load-test the battery", "Check alternator output", "Inspect main grounds and terminal voltage drop"],
    warning: "Low voltage can create misleading faults across many modules, especially on German cars.",
    keywords: ["low voltage", "battery", "alternator", "ground"],
  },
  {
    code: "P0606",
    title: "ECM / PCM processor fault",
    system: "Engine control module",
    severity: "High",
    summary: "The engine controller detected an internal processor or control-module fault.",
    symptoms: ["No start", "Stalling", "Multiple unrelated faults", "Reduced power"],
    likelyCauses: ["Control-module internal failure", "Low voltage or power supply interruption", "Water ingress", "Poor ground or corrupted programming"],
    firstChecks: ["Confirm battery, power, and grounds first", "Check for water ingress or connector corrosion", "Verify software and related voltage faults before replacing the ECU"],
    warning: "ECU replacement is expensive and usually requires programming; prove power and ground integrity first.",
    keywords: ["ECU", "PCM", "processor fault", "module"],
  },
  {
    code: "P0715",
    title: "Input / turbine speed sensor circuit",
    system: "Transmission",
    severity: "High",
    summary: "The transmission controller cannot trust the input or turbine speed signal.",
    symptoms: ["Harsh shifts", "Limp mode", "Delayed engagement", "Incorrect gear display"],
    likelyCauses: ["Failed speed sensor", "Mechatronics wiring issue", "Fluid contamination affecting sensor signal", "Internal transmission fault"],
    firstChecks: ["Scan transmission live speed data", "Check wiring and connector condition", "Review fluid service history and related gearbox faults"],
    warning: "Speed-sensor faults can mimic internal gearbox problems, so read transmission data before approving major repairs.",
    keywords: ["transmission speed sensor", "turbine speed", "gearbox", "mechatronics"],
  },
  {
    code: "P0741",
    title: "Torque converter clutch stuck off / performance",
    system: "Transmission",
    severity: "High",
    summary: "The torque converter clutch is not locking as expected or slip remains too high.",
    symptoms: ["Higher cruising RPM", "Shudder", "Transmission warning", "Poor fuel economy"],
    likelyCauses: ["Torque converter clutch wear", "Valve-body or solenoid fault", "Low or degraded fluid", "Internal pressure-control issue"],
    firstChecks: ["Monitor converter slip during cruise", "Check fluid level and service history", "Scan transmission adaptation and pressure faults"],
    warning: "Ignoring converter slip can contaminate fluid and worsen internal transmission wear.",
    keywords: ["torque converter", "TCC", "transmission shudder", "gearbox"],
  },
  {
    code: "P0750",
    title: "Shift solenoid A malfunction",
    system: "Transmission",
    severity: "High",
    summary: "The transmission controller detected an electrical or hydraulic problem with shift solenoid A.",
    symptoms: ["Harsh shifting", "Missing gears", "Limp mode", "Transmission warning"],
    likelyCauses: ["Failed solenoid", "Valve-body or mechatronics issue", "Wiring fault", "Contaminated or low transmission fluid"],
    firstChecks: ["Scan manufacturer-specific transmission faults", "Check fluid condition and service history", "Test solenoid circuit and connector integrity"],
    warning: "Transmission solenoid faults need gearbox-specific diagnosis; generic OBD data is rarely enough.",
    keywords: ["shift solenoid", "transmission", "mechatronics", "valve body"],
  },
  {
    code: "P0868",
    title: "Transmission fluid pressure low",
    system: "Transmission",
    severity: "High",
    summary: "The transmission controller sees lower hydraulic pressure than required for reliable clutch or gear operation.",
    symptoms: ["Slipping", "Delayed engagement", "Harsh shifts", "Limp mode"],
    likelyCauses: ["Low fluid level", "Fluid leak", "Pump or valve-body problem", "Internal clutch wear"],
    firstChecks: ["Check fluid level with the correct temperature procedure", "Inspect for leaks", "Scan pressure-control and adaptation data"],
    warning: "Do not continue driving a transmission that is slipping from low pressure.",
    keywords: ["transmission pressure", "low fluid", "gearbox slip", "valve body"],
  },
  {
    code: "P2279",
    title: "Intake air system leak",
    system: "Air metering",
    severity: "Medium",
    summary: "The ECU detects extra unmetered air entering the intake system.",
    symptoms: ["Rough idle", "Hissing noise", "Lean faults", "Reduced power"],
    likelyCauses: ["Split intake hose", "PCV failure", "Loose clamp", "Intake manifold or charge-pipe leak"],
    firstChecks: ["Smoke-test the intake and PCV system", "Inspect charge pipes and clamps", "Compare fuel trims at idle and under load"],
    warning: "Unmetered air can create lean running, misfires, and misleading oxygen-sensor faults.",
    keywords: ["intake leak", "vacuum leak", "PCV", "charge pipe"],
  },
];

export function getFaultCode(code: string) {
  return faultCodes.find((item) => item.code.toLowerCase() === code.toLowerCase());
}

export function getLocalizedFaultCodes(locale: Locale) {
  return faultCodes.map((item) => ({
    ...translateValue(locale, item),
    code: item.code,
  }));
}

export function getLocalizedFaultCode(code: string, locale: Locale) {
  const item = getFaultCode(code);
  return item ? { ...translateValue(locale, item), code: item.code } : undefined;
}
