import type { Locale } from "@/lib/i18n";
import { translateValue } from "@/lib/translate";

export type ModelYearData = {
  slug: string;
  modelSlug: string;
  model: string;
  year: number;
  generation: string;
  score: number;
  risk: "Lower" | "Medium" | "Higher";
  title: string;
  description: string;
  verdict: string;
  bestChoice: string;
  avoidIf: string;
  highlights: string[];
  inspection: string[];
  relatedPowertrains: string[];
};

export const modelYears: ModelYearData[] = [
  {
    slug: "bmw-3-series-2018",
    modelSlug: "bmw-3-series",
    model: "BMW 3 Series",
    year: 2018,
    generation: "F30 late production",
    score: 75,
    risk: "Medium",
    title: "2018 BMW 3 Series Reliability and Buying Guide",
    description: "A model-year view of the late F30 BMW 3 Series, including B47/B48 choices, inspection priorities, and ownership risk.",
    verdict: "One of the more mature F30 years. Engine choice, cooling health, oil leaks, and ZF service evidence remain more important than trim level.",
    bestChoice: "A documented B48 petrol or B47 diesel matched to the buyer's driving pattern.",
    avoidIf: "Cooling loss, warning lights, rough cold starts, or gearbox hesitation are explained away without invoices and scan evidence.",
    highlights: ["Late-generation F30 development", "Strong B-series engine choices", "Broad specialist and parts support"],
    inspection: ["Cold-start engine and listen carefully", "Pressure-check cooling system", "Scan all modules", "Verify automatic-transmission servicing"],
    relatedPowertrains: ["bmw-b47", "bmw-b48", "zf-8hp"],
  },
  {
    slug: "bmw-3-series-2020",
    modelSlug: "bmw-3-series",
    model: "BMW 3 Series",
    year: 2020,
    generation: "G20 early production",
    score: 78,
    risk: "Lower",
    title: "2020 BMW 3 Series Reliability and Buying Guide",
    description: "Reliability signals, engine choices, electronics checks, and inspection priorities for the 2020 G20 BMW 3 Series.",
    verdict: "A convincing modern 3 Series when software history, cooling integrity, and complete servicing are confirmed.",
    bestChoice: "A standard-output B48 petrol with full digital and invoice history.",
    avoidIf: "The car has unresolved driver-assistance, cooling, battery-voltage, or drivetrain warnings.",
    highlights: ["Strong B48 and ZF pairing", "Modern safety and infotainment", "Good daily efficiency"],
    inspection: ["Run a BMW-capable full scan", "Test every driver-assistance feature", "Check coolant residue", "Confirm tire and alignment condition"],
    relatedPowertrains: ["bmw-b47", "bmw-b48", "zf-8hp"],
  },
  {
    slug: "mercedes-c-class-2019",
    modelSlug: "mercedes-c-class",
    model: "Mercedes-Benz C-Class",
    year: 2019,
    generation: "W205 facelift",
    score: 73,
    risk: "Medium",
    title: "2019 Mercedes-Benz C-Class Reliability and Buying Guide",
    description: "A focused guide to 2019 W205 C-Class reliability, 9G-Tronic behavior, diesel emissions, electronics, and used-car checks.",
    verdict: "The facelift W205 is refined and mature, but scan quality and emissions-system verification decide whether it is a calm buy.",
    bestChoice: "A petrol or regularly motorway-driven diesel with clean diagnostics and complete servicing.",
    avoidIf: "AdBlue, NOx, battery, gearbox, or electrical warnings are present without a documented diagnosis.",
    highlights: ["Mature W205 platform", "Comfortable long-distance behavior", "Wide engine availability"],
    inspection: ["Check battery and charging voltage", "Scan SCR/NOx systems on diesels", "Test 9G-Tronic cold and hot", "Operate every cabin feature"],
    relatedPowertrains: ["mercedes-om651", "mercedes-9g-tronic"],
  },
  {
    slug: "audi-a4-2018",
    modelSlug: "audi-a4",
    model: "Audi A4",
    year: 2018,
    generation: "B9",
    score: 74,
    risk: "Medium",
    title: "2018 Audi A4 Reliability and Buying Guide",
    description: "2018 Audi A4 B9 reliability, EA888 and TDI checks, S tronic behavior, cooling risks, and pre-purchase priorities.",
    verdict: "A refined B9 year with strong fundamentals. Exact engine code, cooling integrity, oil behavior, and gearbox history still control the risk.",
    bestChoice: "A serviced mainstream engine with clean oil history and smooth S tronic operation.",
    avoidIf: "There is unexplained coolant loss, oil consumption, timing noise, or delayed gearbox engagement.",
    highlights: ["High-quality B9 cabin", "Efficient engine range", "Strong motorway comfort"],
    inspection: ["Identify exact engine and gearbox codes", "Inspect thermostat and coolant system", "Review oil-use history", "Scan gearbox adaptations and faults"],
    relatedPowertrains: ["vag-ea888", "vag-dq250-dsg"],
  },
  {
    slug: "audi-a4-2020",
    modelSlug: "audi-a4",
    model: "Audi A4",
    year: 2020,
    generation: "B9 facelift",
    score: 77,
    risk: "Lower",
    title: "2020 Audi A4 Reliability and Buying Guide",
    description: "2020 facelift Audi A4 reliability, engine and S tronic choices, digital systems, cooling checks, and ownership planning.",
    verdict: "A mature B9 choice with improved technology. Clean cooling, software, gearbox, and service records make it one of the stronger A4 years covered.",
    bestChoice: "A mainstream petrol specification with complete oil, cooling, and transmission records.",
    avoidIf: "Digital-system warnings, coolant loss, oil consumption, or gearbox hesitation remain unresolved.",
    highlights: ["Mature facelift platform", "Efficient modern engines", "Strong cabin technology"],
    inspection: ["Scan driver-assistance modules", "Inspect coolant housings", "Verify S tronic servicing", "Review oil-level history"],
    relatedPowertrains: ["vag-ea888", "vag-dq250-dsg"],
  },
  {
    slug: "volkswagen-golf-2019",
    modelSlug: "volkswagen-golf",
    model: "Volkswagen Golf",
    year: 2019,
    generation: "Golf Mk7.5",
    score: 76,
    risk: "Medium",
    title: "2019 Volkswagen Golf Reliability and Buying Guide",
    description: "A buyer-focused view of the 2019 Golf Mk7.5, covering TSI/TDI engines, DSG servicing, cooling, electronics, and inspection.",
    verdict: "A mature Golf year and a strong all-round used buy when the exact drivetrain has been maintained correctly.",
    bestChoice: "A simple, documented specification with the drivetrain matched to annual mileage.",
    avoidIf: "DSG service is missing, coolant is low, warning lamps are active, or modifications obscure the car's history.",
    highlights: ["Mature Mk7 platform", "Excellent everyday usability", "Good parts availability"],
    inspection: ["Confirm wet- or dry-clutch DSG type", "Check cooling-system residue", "Scan engine and gearbox", "Inspect driver-assistance sensors"],
    relatedPowertrains: ["vag-ea888", "vag-dq250-dsg"],
  },
  {
    slug: "volkswagen-golf-2017",
    modelSlug: "volkswagen-golf",
    model: "Volkswagen Golf",
    year: 2017,
    generation: "Golf Mk7",
    score: 72,
    risk: "Medium",
    title: "2017 Volkswagen Golf Reliability and Buying Guide",
    description: "2017 Golf Mk7 reliability, TSI and TDI choices, DSG history, water-pump checks, and practical used-car inspection advice.",
    verdict: "A well-understood Golf year with broad support. DSG type, cooling history, exact engine code, and usage pattern remain decisive.",
    bestChoice: "A simple, unmodified specification with complete annual servicing and a drivetrain suited to the buyer's mileage.",
    avoidIf: "Coolant loss, DSG shudder, emissions warnings, or tuning modifications complicate the evidence.",
    highlights: ["Proven Mk7 platform", "Excellent parts support", "Strong everyday packaging"],
    inspection: ["Identify exact DSG type", "Inspect water-pump area", "Scan engine and gearbox", "Check for modification history"],
    relatedPowertrains: ["vag-ea888", "vag-dq250-dsg"],
  },
  {
    slug: "bmw-x5-2019",
    modelSlug: "bmw-x5",
    model: "BMW X5",
    year: 2019,
    generation: "G05 early production",
    score: 71,
    risk: "Medium",
    title: "2019 BMW X5 Reliability and Buying Guide",
    description: "2019 BMW X5 G05 ownership risk, air suspension, electronics, B-series engines, xDrive, and pre-purchase inspection priorities.",
    verdict: "Highly capable, but complexity makes a full-system inspection essential. A good engine cannot compensate for neglected chassis electronics or suspension.",
    bestChoice: "A standard, documented six-cylinder specification without unresolved chassis or electrical warnings.",
    avoidIf: "Air suspension sinks, tires mismatch, cooling loss is present, or the scan shows repeated network and chassis faults.",
    highlights: ["Strong long-distance ability", "Excellent drivetrain choices", "Modern cabin and safety technology"],
    inspection: ["Leave air suspension parked and recheck height", "Verify matching tires", "Scan every chassis module", "Inspect cooling and transfer-case behavior"],
    relatedPowertrains: ["bmw-b47", "zf-8hp"],
  },
  {
    slug: "audi-q5-2020",
    modelSlug: "audi-q5",
    model: "Audi Q5",
    year: 2020,
    generation: "FY pre-facelift",
    score: 72,
    risk: "Medium",
    title: "2020 Audi Q5 Reliability and Buying Guide",
    description: "2020 Audi Q5 reliability, EA888/TDI considerations, S tronic, quattro, cooling, and electronic-system checks.",
    verdict: "A polished premium SUV whose risk depends on drivetrain identification, cooling health, gearbox service, and electronic condition.",
    bestChoice: "A mainstream engine with full service records and clean gearbox and quattro diagnostics.",
    avoidIf: "The seller cannot explain coolant loss, drivetrain vibration, warning lights, or missing transmission service.",
    highlights: ["Refined cabin", "Secure road manners", "Useful family packaging"],
    inspection: ["Confirm actual quattro system", "Check gearbox service history", "Inspect cooling housings", "Test MMI and driver-assistance systems"],
    relatedPowertrains: ["vag-ea888", "vag-dq250-dsg"],
  },
  {
    slug: "volkswagen-tiguan-2020",
    modelSlug: "volkswagen-tiguan",
    model: "Volkswagen Tiguan",
    year: 2020,
    generation: "Second generation",
    score: 70,
    risk: "Medium",
    title: "2020 Volkswagen Tiguan Reliability and Buying Guide",
    description: "2020 Volkswagen Tiguan reliability, TSI/TDI and DSG checks, 4Motion servicing, cooling leaks, and ownership planning.",
    verdict: "A practical family SUV that can be a sensible buy, provided DSG, cooling, emissions, and 4Motion servicing are verified.",
    bestChoice: "A modest-output, unmodified car with complete annual service and drivetrain records.",
    avoidIf: "There is DSG shudder, coolant residue, diesel emissions trouble, or mismatched tires on a 4Motion car.",
    highlights: ["Practical interior", "Wide drivetrain choice", "Good independent support"],
    inspection: ["Test DSG in slow traffic", "Check Haldex/4Motion service", "Inspect water-pump area", "Scan emissions systems on diesels"],
    relatedPowertrains: ["vag-ea888", "vag-dq250-dsg"],
  },
  {
    slug: "bmw-4-series-2020",
    modelSlug: "bmw-4-series",
    model: "BMW 4 Series",
    year: 2020,
    generation: "F32/F36 late production",
    score: 74,
    risk: "Medium",
    title: "2020 BMW 4 Series Reliability and Buying Guide",
    description: "A model-year view of the late BMW 4 Series, including B48/B47 choices, ZF gearbox checks, coupe body condition, and ownership risk.",
    verdict: "A mature late-generation 4 Series. It is strongest when cooling health, oil leaks, tire quality, and ZF service evidence are all clear.",
    bestChoice: "A documented B48 petrol or clean B47 diesel with standard suspension and complete service records.",
    avoidIf: "Cold-start noise, coolant loss, roof or water-ingress issues, gearbox hesitation, or modification history are brushed aside.",
    highlights: ["Late F32/F36 development", "Strong B-series engine options", "Good specialist support"],
    inspection: ["Listen from cold for timing and misfire clues", "Inspect coolant and oil-leak areas", "Scan engine and gearbox modules", "Check coupe or Gran Coupe body seals"],
    relatedPowertrains: ["bmw-b47", "bmw-b48", "zf-8hp"],
  },
  {
    slug: "bmw-7-series-2020",
    modelSlug: "bmw-7-series",
    model: "BMW 7 Series",
    year: 2020,
    generation: "G11/G12 facelift",
    score: 70,
    risk: "Medium",
    title: "2020 BMW 7 Series Reliability and Buying Guide",
    description: "2020 BMW 7 Series reliability, luxury electronics, air suspension, B57/B58 checks, ZF gearbox behavior, and buying priorities.",
    verdict: "A refined flagship when maintained properly. The purchase only makes sense after clean module scans, working luxury equipment, and documented suspension and fluid service.",
    bestChoice: "A six-cylinder diesel or petrol with complete BMW specialist history and no unresolved chassis or electrical warnings.",
    avoidIf: "Air suspension sag, battery-voltage faults, coolant loss, dead comfort features, or emissions warnings appear during inspection.",
    highlights: ["Facelift luxury technology", "Strong six-cylinder choices", "Excellent long-distance comfort"],
    inspection: ["Scan every module", "Check air suspension after sitting", "Test all comfort and driver-assistance features", "Verify gearbox and brake-fluid history"],
    relatedPowertrains: ["zf-8hp", "bmw-b48"],
  },
  {
    slug: "bmw-x1-2021",
    modelSlug: "bmw-x1",
    model: "BMW X1",
    year: 2021,
    generation: "F48 facelift",
    score: 73,
    risk: "Medium",
    title: "2021 BMW X1 Reliability and Buying Guide",
    description: "2021 BMW X1 reliability, B47/B48 engine checks, xDrive tire sensitivity, gearbox behavior, and compact SUV inspection advice.",
    verdict: "A useful compact BMW SUV with mature hardware. It is best bought with clean emissions data, matched tires, and smooth gearbox behavior.",
    bestChoice: "A documented petrol or regularly motorway-used diesel with matching tires and clean diagnostics.",
    avoidIf: "The car shows xDrive vibration, diesel emissions faults, coolant residue, rough shifts, or mismatched tire wear.",
    highlights: ["Facelift F48 updates", "Compact SUV practicality", "Efficient B-series engines"],
    inspection: ["Check tire match and tread depth", "Scan xDrive and gearbox modules", "Inspect cooling and oil-leak areas", "Review diesel emissions data where applicable"],
    relatedPowertrains: ["bmw-b47", "bmw-b48"],
  },
  {
    slug: "mercedes-cla-2020",
    modelSlug: "mercedes-cla",
    model: "Mercedes-Benz CLA",
    year: 2020,
    generation: "C118 early production",
    score: 71,
    risk: "Medium",
    title: "2020 Mercedes-Benz CLA Reliability and Buying Guide",
    description: "2020 Mercedes-Benz CLA reliability, 7G/8G-DCT behavior, petrol and diesel checks, electronics, and compact saloon buying advice.",
    verdict: "A stylish modern CLA that needs proper diagnostic work. Gearbox behavior, battery health, electronics, and emissions data decide whether it is a calm buy.",
    bestChoice: "A mainstream petrol with clean Mercedes diagnostics, smooth DCT behavior, and complete service history.",
    avoidIf: "DCT hesitation, AdBlue/NOx warnings, weak-battery faults, accident repairs, or unresolved infotainment issues are present.",
    highlights: ["Modern C118 cabin", "Efficient compact engines", "Strong style and equipment"],
    inspection: ["Run a Mercedes-capable scan", "Test DCT in traffic and reverse", "Check battery voltage and warning history", "Inspect paint, wheels, and suspension"],
    relatedPowertrains: ["mercedes-om651"],
  },
  {
    slug: "mercedes-gla-2020",
    modelSlug: "mercedes-gla",
    model: "Mercedes-Benz GLA",
    year: 2020,
    generation: "H247 early production",
    score: 70,
    risk: "Medium",
    title: "2020 Mercedes-Benz GLA Reliability and Buying Guide",
    description: "2020 Mercedes-Benz GLA reliability, compact SUV electronics, DCT behavior, 4Matic checks, diesel emissions, and inspection priorities.",
    verdict: "A more practical GLA generation, but early modern electronics and DCT behavior need a careful scan and proper road test.",
    bestChoice: "A petrol or low-risk diesel with complete digital history, clean module scans, and no 4Matic or gearbox symptoms.",
    avoidIf: "Battery, driver-assistance, DCT, AdBlue, NOx, or 4Matic warnings remain unexplained.",
    highlights: ["More useful cabin than earlier GLA", "Modern Mercedes technology", "Compact SUV packaging"],
    inspection: ["Scan engine, gearbox, body, and driver-assistance modules", "Test DCT shifts cold and warm", "Inspect tires and suspension", "Check emissions readiness on diesels"],
    relatedPowertrains: ["mercedes-om651"],
  },
  {
    slug: "mercedes-gle-2019",
    modelSlug: "mercedes-gle",
    model: "Mercedes-Benz GLE",
    year: 2019,
    generation: "W167 early production",
    score: 69,
    risk: "Medium",
    title: "2019 Mercedes-Benz GLE Reliability and Buying Guide",
    description: "2019 Mercedes-Benz GLE reliability, W167 electronics, Airmatic checks, diesel emissions, 4Matic, and large SUV buying advice.",
    verdict: "A comfortable and capable SUV, but early W167 complexity makes diagnostics essential. Suspension, electronics, tires, brakes, and emissions systems need proof.",
    bestChoice: "A standard diesel specification with clean Mercedes diagnostics, documented servicing, and no air-suspension or emissions warnings.",
    avoidIf: "Airmatic sag, weak battery behavior, AdBlue/NOx faults, mismatched tires, or rough gearbox behavior appear.",
    highlights: ["Modern W167 platform", "Excellent comfort and space", "Strong long-distance ability"],
    inspection: ["Check ride height after sitting", "Scan all chassis and emissions modules", "Inspect tire match and brake wear", "Test every camera and driver-assistance feature"],
    relatedPowertrains: ["mercedes-9g-tronic"],
  },
  {
    slug: "audi-a1-2019",
    modelSlug: "audi-a1",
    model: "Audi A1",
    year: 2019,
    generation: "GB second generation",
    score: 72,
    risk: "Medium",
    title: "2019 Audi A1 Reliability and Buying Guide",
    description: "2019 Audi A1 reliability, TFSI checks, S tronic behavior, timing evidence, city-car wear, and used buying advice.",
    verdict: "A modern small Audi that is best judged by drivetrain and city-use wear. Clean service records and smooth S tronic behavior are more important than trim.",
    bestChoice: "A simple TFSI model with complete servicing, no gearbox symptoms, and tidy wheel/suspension condition.",
    avoidIf: "Timing noise, misfires, rough S tronic engagement, coolant loss, or accident-repair clues are present.",
    highlights: ["Modern second-generation cabin", "Low running costs", "Shared VAG platform knowledge"],
    inspection: ["Scan engine and gearbox", "Test S tronic in slow traffic", "Check coolant and misfire history", "Inspect wheels, tires, brakes, and paint repairs"],
    relatedPowertrains: ["vag-dq250-dsg"],
  },
  {
    slug: "audi-q3-2020",
    modelSlug: "audi-q3",
    model: "Audi Q3",
    year: 2020,
    generation: "F3 second generation",
    score: 71,
    risk: "Medium",
    title: "2020 Audi Q3 Reliability and Buying Guide",
    description: "2020 Audi Q3 reliability, EA888 and TDI checks, S tronic, quattro/Haldex service, electronics, and compact SUV buying priorities.",
    verdict: "A well-rounded compact SUV when drivetrain details are known. S tronic service, Haldex history, cooling health, and scan data decide the risk.",
    bestChoice: "A mainstream petrol or diesel with documented S tronic service and clean quattro/Haldex evidence if fitted.",
    avoidIf: "There is gearbox judder, coolant loss, oil consumption, Haldex neglect, or diesel emissions warning history.",
    highlights: ["Modern F3 cabin", "Useful compact SUV layout", "Shared VAG drivetrain support"],
    inspection: ["Confirm engine and gearbox codes", "Scan engine, gearbox, AWD, and body modules", "Check Haldex service on quattro cars", "Inspect coolant and tire wear"],
    relatedPowertrains: ["vag-ea888", "vag-dq250-dsg"],
  },
  {
    slug: "volkswagen-arteon-2019",
    modelSlug: "volkswagen-arteon",
    model: "Volkswagen Arteon",
    year: 2019,
    generation: "First generation",
    score: 72,
    risk: "Medium",
    title: "2019 Volkswagen Arteon Reliability and Buying Guide",
    description: "2019 Volkswagen Arteon reliability, TDI/TSI engines, DSG service, 4Motion/Haldex checks, electronics, and ownership planning.",
    verdict: "A strong value fastback when maintained properly. DSG, cooling, emissions, Haldex, and option-heavy electronics need the same seriousness as premium rivals.",
    bestChoice: "A documented 2.0 TDI or TSI with DSG service proof and no unresolved driver-assistance faults.",
    avoidIf: "DSG service is missing, coolant loss is visible, AdBlue/DPF faults are present, or 4Motion service history is unclear.",
    highlights: ["Passat-family engineering", "Premium-feeling cabin", "Strong long-distance comfort"],
    inspection: ["Verify DSG service", "Check Haldex history on 4Motion cars", "Scan emissions and driver-assistance modules", "Inspect coolant and oil-leak areas"],
    relatedPowertrains: ["vag-ea888", "vag-dq250-dsg"],
  },
  {
    slug: "volkswagen-t-roc-2021",
    modelSlug: "volkswagen-t-roc",
    model: "Volkswagen T-Roc",
    year: 2021,
    generation: "First generation",
    score: 73,
    risk: "Medium",
    title: "2021 Volkswagen T-Roc Reliability and Buying Guide",
    description: "2021 Volkswagen T-Roc reliability, TSI/TDI engine checks, DSG behavior, 4Motion service, cooling, and compact crossover inspection advice.",
    verdict: "A sensible compact crossover when bought with clear records. It is strongest as a simple TSI or documented diesel with clean DSG and cooling checks.",
    bestChoice: "A modest-output TSI with complete annual servicing, clean scan data, and no DSG or cooling symptoms.",
    avoidIf: "DSG judder, coolant residue, DPF/EGR warnings, Haldex service gaps, or hard urban wear are visible.",
    highlights: ["Golf-family practicality", "Compact crossover size", "Good parts availability"],
    inspection: ["Scan engine and gearbox modules", "Test DSG or clutch in traffic", "Check coolant and water-pump area", "Inspect tires, wheels, suspension, and parking damage"],
    relatedPowertrains: ["vag-ea888", "vag-dq250-dsg"],
  },
];

export function getModelYear(slug: string) {
  return modelYears.find((item) => item.slug === slug);
}

export function getLocalizedModelYears(locale: Locale) {
  return modelYears.map((item) => ({
    ...translateValue(locale, item),
    slug: item.slug,
    modelSlug: item.modelSlug,
    relatedPowertrains: item.relatedPowertrains,
  }));
}

export function getLocalizedModelYear(slug: string, locale: Locale) {
  const item = getModelYear(slug);
  return item
    ? {
        ...translateValue(locale, item),
        slug: item.slug,
        modelSlug: item.modelSlug,
        relatedPowertrains: item.relatedPowertrains,
      }
    : undefined;
}
