import type { Locale } from "@/lib/i18n";
import { translateValue } from "@/lib/translate";

export type PartsFailureItem = {
  slug: string;
  brand: "BMW" | "Mercedes-Benz" | "Audi" | "Volkswagen";
  brandHref: string;
  system: string;
  title: string;
  summary: string;
  affected: string[];
  symptoms: string[];
  faultCodes: string[];
  whyItFails: string[];
  repairDifficulty: "Low" | "Medium" | "High";
  estimatedCost: string;
  checksBeforeBuying: string[];
  relatedModels: { label: string; href: string }[];
  relatedPowertrains: { label: string; href: string }[];
  relatedGuides: { label: string; href: string }[];
};

const bmwModels = [{ label: "BMW 3 Series", href: "/models/bmw-3-series" }];
const mercedesModels = [{ label: "Mercedes C-Class", href: "/models/mercedes-c-class" }];
const audiModels = [{ label: "Audi A4", href: "/models/audi-a4" }];
const volkswagenModels = [{ label: "Volkswagen Golf", href: "/models/volkswagen-golf" }];
const buyerGuides = [
  { label: "Used-car checklist", href: "/buying-checklist" },
  { label: "Used German car red flags", href: "/blog/seven-red-flags-before-buying-used-german-car" },
];

export const partsFailureItems: PartsFailureItem[] = [
  {
    slug: "bmw-n47-timing-chain",
    brand: "BMW",
    brandHref: "/brands/bmw",
    system: "Timing chain",
    title: "BMW N47 Timing Chain",
    summary:
      "Rear-mounted N47 timing-chain wear is a major buyer risk because noise, service history, and repair access decide whether the car is affordable or a trap.",
    affected: ["BMW 1 Series, 3 Series, 5 Series, X1, X3 diesel models using N47 variants"],
    symptoms: ["Cold-start rattle", "Metallic chain noise at idle", "Timing correlation faults", "Hard starting or rough running"],
    faultCodes: ["P0016", "P0340", "P0335"],
    whyItFails: ["Long oil intervals accelerate chain and guide wear.", "Rear engine placement makes repair labor intensive.", "Ignored early noise can become catastrophic timing failure."],
    repairDifficulty: "High",
    estimatedCost: "High, because engine access and labor dominate the job.",
    checksBeforeBuying: ["Listen from cold near the rear of the engine.", "Reject cars with vague oil-service history.", "Ask for chain repair invoices if mileage is high.", "Scan for timing and cam/crank correlation faults."],
    relatedModels: bmwModels,
    relatedPowertrains: [{ label: "BMW N47", href: "/powertrains/bmw-n47" }],
    relatedGuides: buyerGuides,
  },
  {
    slug: "bmw-b47-egr-cooler",
    brand: "BMW",
    brandHref: "/brands/bmw",
    system: "EGR cooler",
    title: "BMW B47 EGR Cooler",
    summary:
      "B47 EGR cooler condition matters before buying because coolant loss, recall history, and emissions faults can hide behind a normal-looking dashboard.",
    affected: ["BMW B47 diesel models including 1 Series, 3 Series, 5 Series, X3, and related MINI models"],
    symptoms: ["Coolant loss", "Exhaust smell", "Reduced power", "EGR or DPF warnings"],
    faultCodes: ["P0401", "P2002", "P2458"],
    whyItFails: ["Thermal cycling stresses the cooler.", "Soot and condensation can contaminate the EGR path.", "Recall/campaign work may be incomplete or poorly documented."],
    repairDifficulty: "Medium",
    estimatedCost: "Medium to high depending on access and whether associated parts are replaced.",
    checksBeforeBuying: ["Check BMW recall/campaign history.", "Inspect coolant level and EGR area.", "Scan EGR command, DPF load, and stored emissions faults.", "Ask for proof of cooler replacement where applicable."],
    relatedModels: bmwModels,
    relatedPowertrains: [{ label: "BMW B47", href: "/powertrains/bmw-b47" }],
    relatedGuides: buyerGuides,
  },
  {
    slug: "bmw-b48-coolant-system",
    brand: "BMW",
    brandHref: "/brands/bmw",
    system: "Cooling system",
    title: "BMW B48 Coolant System",
    summary:
      "B48 cooling-system leaks can turn a good petrol BMW into a costly purchase if coolant residue, thermostat behavior, and service proof are ignored.",
    affected: ["BMW B48 petrol models including 1 Series, 3 Series, 5 Series, X1, X3, and MINI Cooper S variants"],
    symptoms: ["Low coolant warning", "Sweet smell", "Temperature instability", "Residue around plastic cooling parts"],
    faultCodes: ["P0128", "P0118", "P0300"],
    whyItFails: ["Plastic housings and seals age under heat.", "Small leaks are often topped up instead of repaired.", "Overheating can trigger secondary misfire or head-gasket concerns."],
    repairDifficulty: "Medium",
    estimatedCost: "Medium, but rises quickly if overheating damage is present.",
    checksBeforeBuying: ["Inspect when fully warm after the test drive.", "Check coolant color, level, and pressure behavior.", "Ask whether pump, thermostat, hoses, and coolant were replaced together.", "Avoid any car with overheating history."],
    relatedModels: bmwModels,
    relatedPowertrains: [{ label: "BMW B48", href: "/powertrains/bmw-b48" }],
    relatedGuides: buyerGuides,
  },
  {
    slug: "bmw-zf-8hp-gearbox",
    brand: "BMW",
    brandHref: "/brands/bmw",
    system: "Automatic gearbox",
    title: "BMW ZF 8HP Gearbox",
    summary:
      "The ZF 8HP is respected, but used-car buyers still need to check fluid history, torque-converter behavior, adaptations, and engine faults that mimic gearbox issues.",
    affected: ["Many BMW longitudinal automatic models including 3 Series, 5 Series, X3, X5, and 7 Series"],
    symptoms: ["Delayed engagement", "Harsh downshift", "Lock-up shudder", "Transmission warning"],
    faultCodes: ["P0700", "P0730", "P0741", "P0868"],
    whyItFails: ["Fluid is often treated as lifetime fill.", "High torque, heat, towing, and neglected service stress clutches.", "Engine misfires or voltage issues can create false gearbox complaints."],
    repairDifficulty: "Medium",
    estimatedCost: "Medium for service; high for mechatronic or internal repair.",
    checksBeforeBuying: ["Drive cold and warm in traffic and at cruise.", "Check for fluid-service invoices.", "Scan TCU and engine modules together.", "Budget preventive service if records are missing."],
    relatedModels: [{ label: "BMW 5 Series", href: "/models/bmw-5-series" }, { label: "BMW X5", href: "/models/bmw-x5" }],
    relatedPowertrains: [{ label: "ZF 8HP", href: "/powertrains/zf-8hp" }],
    relatedGuides: buyerGuides,
  },
  {
    slug: "bmw-turbo-actuator",
    brand: "BMW",
    brandHref: "/brands/bmw",
    system: "Turbo actuator",
    title: "BMW Turbo Actuator",
    summary:
      "BMW turbo actuator faults often appear as underboost or overboost, so buyers should verify boost control rather than replacing parts by guesswork.",
    affected: ["BMW diesel and turbo petrol models with electronic or vacuum-actuated variable turbo control"],
    symptoms: ["Limp mode", "Whistling", "Poor acceleration", "Overboost or underboost codes"],
    faultCodes: ["P0299", "P0234", "P0101"],
    whyItFails: ["Soot, heat, vacuum leaks, wiring faults, or actuator wear affect boost control.", "Sticking turbo geometry can be mistaken for a sensor issue.", "Cheap repairs often ignore intake and exhaust restrictions."],
    repairDifficulty: "Medium",
    estimatedCost: "Medium, but high if the turbo itself is worn.",
    checksBeforeBuying: ["Log requested vs actual boost.", "Inspect boost pipes, vacuum lines, and actuator movement.", "Check for smoke under load.", "Scan before and after a hard test drive."],
    relatedModels: bmwModels,
    relatedPowertrains: [{ label: "BMW B47", href: "/powertrains/bmw-b47" }],
    relatedGuides: buyerGuides,
  },
  {
    slug: "mercedes-om651-timing-chain",
    brand: "Mercedes-Benz",
    brandHref: "/brands/mercedes-benz",
    system: "Timing chain",
    title: "Mercedes OM651 Timing Chain",
    summary:
      "OM651 timing-chain condition is a key used-diesel check because noise, oil history, and access can turn a normal C-Class or E-Class into an expensive repair.",
    affected: ["Mercedes C-Class, E-Class, A-Class, GLC, and other OM651 diesel applications"],
    symptoms: ["Cold-start rattle", "Rough start", "Timing faults", "Diesel knock"],
    faultCodes: ["P0016", "P0340", "P0335"],
    whyItFails: ["Long oil intervals and high mileage increase chain and tensioner wear.", "Rear placement makes repair labor heavy.", "Noise is often minimized by sellers."],
    repairDifficulty: "High",
    estimatedCost: "High because access and labor are substantial.",
    checksBeforeBuying: ["Listen from cold start.", "Check oil-service dates and mileage intervals.", "Ask for timing repair evidence on high-mileage cars.", "Scan for cam/crank correlation faults."],
    relatedModels: mercedesModels,
    relatedPowertrains: [{ label: "Mercedes OM651", href: "/powertrains/mercedes-om651" }],
    relatedGuides: buyerGuides,
  },
  {
    slug: "mercedes-om654-adblue-system",
    brand: "Mercedes-Benz",
    brandHref: "/brands/mercedes-benz",
    system: "AdBlue / SCR",
    title: "Mercedes OM654 AdBlue System",
    summary:
      "OM654 AdBlue system faults can create countdown warnings and expensive diagnosis, so buyers should check SCR readiness, NOx data, and repair history.",
    affected: ["Modern Mercedes diesel models using OM654 engines and SCR/AdBlue emissions systems"],
    symptoms: ["AdBlue countdown", "Check-engine light", "No-start warning", "NOx efficiency faults"],
    faultCodes: ["P204F", "P20EE", "P2002"],
    whyItFails: ["NOx sensors, dosing units, tank heaters, and software all interact.", "Short trips and poor battery health can complicate diagnosis.", "Cleared codes can return after a full drive cycle."],
    repairDifficulty: "Medium",
    estimatedCost: "Medium to high depending on sensor/tank/module involvement.",
    checksBeforeBuying: ["Scan SCR and NOx modules with Mercedes-capable diagnostics.", "Check for countdown history and recent code clearing.", "Verify AdBlue tank, injector, and NOx sensor invoices.", "Drive long enough for readiness checks."],
    relatedModels: mercedesModels,
    relatedPowertrains: [{ label: "Mercedes OM651 vs OM654", href: "/compare/mercedes-om651-vs-om654" }],
    relatedGuides: buyerGuides,
  },
  {
    slug: "mercedes-9g-tronic-gearbox",
    brand: "Mercedes-Benz",
    brandHref: "/brands/mercedes-benz",
    system: "Automatic gearbox",
    title: "Mercedes 9G-Tronic Gearbox",
    summary:
      "9G-Tronic issues are usually about service, calibration, voltage, or torque-converter behavior, so a proper test drive matters more than a quick spin.",
    affected: ["Mercedes C-Class, E-Class, GLC, GLE, and many newer longitudinal automatic models"],
    symptoms: ["Low-speed bump", "Delayed drive", "Harsh downshift", "Torque-converter shudder"],
    faultCodes: ["P0700", "P0730", "P0741", "P0868"],
    whyItFails: ["Fluid service may be delayed.", "Adaptations can drift after repairs or weak battery events.", "Engine torque faults can feel like gearbox faults."],
    repairDifficulty: "Medium",
    estimatedCost: "Medium for service/adaptation; high for internal repair.",
    checksBeforeBuying: ["Test cold, hot, reverse, hill starts, and light-throttle cruise.", "Scan TCU and voltage history.", "Ask for gearbox fluid/filter proof.", "Check engine faults before blaming the transmission."],
    relatedModels: mercedesModels,
    relatedPowertrains: [{ label: "Mercedes 9G-Tronic", href: "/powertrains/mercedes-9g-tronic" }],
    relatedGuides: buyerGuides,
  },
  {
    slug: "mercedes-nox-sensors",
    brand: "Mercedes-Benz",
    brandHref: "/brands/mercedes-benz",
    system: "NOx sensors",
    title: "Mercedes NOx Sensors",
    summary:
      "NOx sensor faults are common on modern Mercedes diesels and can be tied to AdBlue/SCR efficiency, software, wiring, and driving pattern.",
    affected: ["Mercedes diesel and petrol models with NOx monitoring, especially Euro 6 diesel applications"],
    symptoms: ["Check-engine light", "AdBlue warning", "Emissions readiness failure", "Countdown message"],
    faultCodes: ["P20EE", "P204F", "U0100"],
    whyItFails: ["Sensors live in high-heat exhaust flow.", "Wiring, control units, and SCR efficiency can all influence the reading.", "Cheap generic sensors may not solve the root cause."],
    repairDifficulty: "Medium",
    estimatedCost: "Medium to high depending on sensor count and coding needs.",
    checksBeforeBuying: ["Scan actual NOx sensor values and SCR efficiency.", "Ask whether genuine or coded sensors were installed.", "Drive until emissions monitors run.", "Treat cleared codes as unresolved until readiness is complete."],
    relatedModels: mercedesModels,
    relatedPowertrains: [{ label: "Mercedes OM651", href: "/powertrains/mercedes-om651" }],
    relatedGuides: buyerGuides,
  },
  {
    slug: "mercedes-air-suspension",
    brand: "Mercedes-Benz",
    brandHref: "/brands/mercedes-benz",
    system: "Air suspension",
    title: "Mercedes Air Suspension",
    summary:
      "Mercedes air suspension gives excellent comfort but can create high used-car risk when compressors, bags, valves, and height sensors age.",
    affected: ["Mercedes E-Class, S-Class, GLE, GLS, and higher-spec models with Airmatic or air suspension"],
    symptoms: ["Car drops overnight", "Compressor runs often", "Uneven ride height", "Suspension warning"],
    faultCodes: ["C1130", "U0121", "P0562"],
    whyItFails: ["Air springs crack with age.", "Leaks overwork the compressor.", "Height sensors, valves, and voltage issues can produce misleading symptoms."],
    repairDifficulty: "Medium",
    estimatedCost: "Medium to very high depending on how many corners and compressor parts need work.",
    checksBeforeBuying: ["View the car after sitting overnight.", "Cycle height modes and listen to compressor run time.", "Inspect each air spring for cracking.", "Scan chassis/suspension modules."],
    relatedModels: [{ label: "Mercedes E-Class", href: "/models/mercedes-e-class" }, { label: "Mercedes S-Class", href: "/models/mercedes-s-class" }],
    relatedPowertrains: [],
    relatedGuides: buyerGuides,
  },
  {
    slug: "audi-ea888-water-pump-thermostat",
    brand: "Audi",
    brandHref: "/brands/audi",
    system: "Water pump / thermostat",
    title: "Audi EA888 Water Pump and Thermostat",
    summary:
      "EA888 water pump and thermostat leakage is one of the most important cooling checks on used Audi TFSI models.",
    affected: ["Audi A3, A4, A5, Q3, Q5 and other EA888 TFSI applications"],
    symptoms: ["Coolant loss", "Sweet smell", "White/pink residue", "Slow warm-up or overheating"],
    faultCodes: ["P0128", "P0118", "P0171"],
    whyItFails: ["Plastic housings and seals age under heat.", "Coolant leaks can be hidden under covers.", "Overheating creates secondary engine risk."],
    repairDifficulty: "Medium",
    estimatedCost: "Medium, higher if overheating damage or access issues are present.",
    checksBeforeBuying: ["Inspect the pump housing after a full warm-up.", "Check coolant level and top-up history.", "Scan coolant temperature behavior.", "Ask for pump/thermostat invoices."],
    relatedModels: audiModels,
    relatedPowertrains: [{ label: "VAG EA888", href: "/powertrains/vag-ea888" }],
    relatedGuides: buyerGuides,
  },
  {
    slug: "audi-20-tdi-egr-dpf",
    brand: "Audi",
    brandHref: "/brands/audi",
    system: "EGR / DPF",
    title: "Audi 2.0 TDI EGR and DPF",
    summary:
      "Audi 2.0 TDI EGR and DPF issues are often usage-related, so buyers should check soot load, regeneration history, and city-driving evidence.",
    affected: ["Audi A3, A4, A5, A6, Q3, Q5 2.0 TDI models"],
    symptoms: ["Limp mode", "Frequent regeneration", "Smoke", "Poor fuel economy"],
    faultCodes: ["P0401", "P2002", "P2458", "P0299"],
    whyItFails: ["Short trips prevent complete regeneration.", "EGR deposits restrict flow.", "Boost leaks and sensor faults can accelerate soot loading."],
    repairDifficulty: "Medium",
    estimatedCost: "Medium to high depending on DPF condition and access.",
    checksBeforeBuying: ["Scan DPF soot/load and EGR data.", "Ask about driving pattern.", "Check for DPF delete or illegal modifications.", "Perform a long test drive and rescan."],
    relatedModels: audiModels,
    relatedPowertrains: [],
    relatedGuides: buyerGuides,
  },
  {
    slug: "audi-s-tronic-mechatronic",
    brand: "Audi",
    brandHref: "/brands/audi",
    system: "S tronic mechatronic",
    title: "Audi S tronic Mechatronic",
    summary:
      "Audi S tronic mechatronic problems can hide until the gearbox is hot, making a proper city test drive and TCU scan essential.",
    affected: ["Audi A3, A4, A5, Q3, Q5 and other S tronic / DSG-family applications"],
    symptoms: ["Delayed reverse", "Harsh shift", "PRNDS warning", "Clutch judder"],
    faultCodes: ["P0700", "P0730", "P0715", "P0750", "P0868"],
    whyItFails: ["Hydraulic pressure, solenoids, clutch wear, and fluid condition all interact.", "Missing gearbox service increases risk.", "Voltage issues can mimic mechatronic failure."],
    repairDifficulty: "High",
    estimatedCost: "High for mechatronic or clutch repair; medium for preventive service.",
    checksBeforeBuying: ["Identify exact S tronic variant.", "Scan gearbox module and adaptations.", "Test in traffic until fully warm.", "Ask for gearbox oil service records."],
    relatedModels: [{ label: "Audi A3", href: "/models/audi-a3" }, { label: "Audi A4", href: "/models/audi-a4" }],
    relatedPowertrains: [{ label: "VAG DQ250 DSG", href: "/powertrains/vag-dq250-dsg" }],
    relatedGuides: buyerGuides,
  },
  {
    slug: "audi-timing-chain-tensioner",
    brand: "Audi",
    brandHref: "/brands/audi",
    system: "Timing chain tensioner",
    title: "Audi Timing Chain Tensioner",
    summary:
      "Timing-chain tensioner condition matters on several Audi petrol engines because startup rattle and correlation faults can point to expensive chain work.",
    affected: ["Selected Audi TFSI engines with chain-driven timing systems, including EA888 generations"],
    symptoms: ["Startup rattle", "Rough idle", "Timing faults", "Poor running"],
    faultCodes: ["P0016", "P0011", "P0340"],
    whyItFails: ["Tensioner design, oil interval, and chain stretch can reduce timing control.", "Early rattle is often ignored.", "Incorrect oil or low oil level worsens wear."],
    repairDifficulty: "High",
    estimatedCost: "High when chain, guides, tensioner, and labor are included.",
    checksBeforeBuying: ["Listen after an overnight cold start.", "Check timing adaptation values when possible.", "Verify chain/tensioner revision work.", "Reject cars with persistent correlation codes."],
    relatedModels: audiModels,
    relatedPowertrains: [{ label: "VAG EA888", href: "/powertrains/vag-ea888" }],
    relatedGuides: buyerGuides,
  },
  {
    slug: "audi-oil-consumption",
    brand: "Audi",
    brandHref: "/brands/audi",
    system: "Oil consumption",
    title: "Audi Oil Consumption",
    summary:
      "Audi oil consumption can be normal usage, PCV trouble, turbo leakage, or deeper piston-ring risk, so buyers need evidence rather than reassurance.",
    affected: ["Audi TFSI engines, especially older/high-mileage examples and poorly serviced cars"],
    symptoms: ["Low oil warning", "Blue smoke", "Oil smell", "Fouled plugs or misfires"],
    faultCodes: ["P0171", "P0300", "P0301", "P0420"],
    whyItFails: ["PCV faults, ring wear, turbo seals, and long oil intervals can all increase consumption.", "Sellers may top up before viewing.", "Catalysts and plugs can suffer secondary damage."],
    repairDifficulty: "High",
    estimatedCost: "Low for PCV; high if internal engine wear is confirmed.",
    checksBeforeBuying: ["Ask how much oil the car uses per 1,000 km.", "Inspect plugs, exhaust smoke, and service invoices.", "Check PCV history and oil grade.", "Avoid cars with unexplained low-oil warnings."],
    relatedModels: audiModels,
    relatedPowertrains: [{ label: "VAG EA888", href: "/powertrains/vag-ea888" }],
    relatedGuides: buyerGuides,
  },
  {
    slug: "volkswagen-dsg-mechatronic",
    brand: "Volkswagen",
    brandHref: "/brands/volkswagen",
    system: "DSG mechatronic",
    title: "Volkswagen DSG Mechatronic",
    summary:
      "Volkswagen DSG mechatronic faults can be expensive, but a proper gearbox-code check, service review, scan, and warm test drive reduce buyer risk.",
    affected: ["VW Golf, Passat, Tiguan, Polo and other DSG-equipped Volkswagen models"],
    symptoms: ["Delayed engagement", "Harsh shifts", "Flashing gear indicator", "Failsafe mode"],
    faultCodes: ["P0700", "P0730", "P0715", "P0750", "P0868"],
    whyItFails: ["Hydraulic pressure, solenoids, clutch wear, heat, and fluid condition all matter.", "Some DSG variants have different service needs.", "Weak battery voltage can create misleading faults."],
    repairDifficulty: "High",
    estimatedCost: "Medium for service, high for mechatronic or clutch repair.",
    checksBeforeBuying: ["Identify gearbox code.", "Scan TCU fault memory.", "Test in stop-start traffic until hot.", "Ask for DSG oil service proof."],
    relatedModels: volkswagenModels,
    relatedPowertrains: [{ label: "VAG DQ250 DSG", href: "/powertrains/vag-dq250-dsg" }],
    relatedGuides: buyerGuides,
  },
  {
    slug: "volkswagen-20-tdi-dpf-egr",
    brand: "Volkswagen",
    brandHref: "/brands/volkswagen",
    system: "DPF / EGR",
    title: "Volkswagen 2.0 TDI DPF and EGR",
    summary:
      "VW 2.0 TDI DPF and EGR faults are strongly linked to driving pattern, maintenance, boost leaks, and whether previous faults were properly fixed.",
    affected: ["Volkswagen Golf, Passat, Tiguan, Touran and other 2.0 TDI models"],
    symptoms: ["Limp mode", "DPF warning", "Smoke", "Poor boost response"],
    faultCodes: ["P0401", "P2002", "P2458", "P0299"],
    whyItFails: ["Short trips, failed sensors, intake leaks, and EGR deposits raise soot load.", "Forced regens can hide root causes temporarily.", "Illegal deletes create inspection and resale risk."],
    repairDifficulty: "Medium",
    estimatedCost: "Medium to high depending on DPF and EGR access.",
    checksBeforeBuying: ["Scan soot load and regeneration data.", "Ask about commute pattern.", "Inspect for DPF/EGR delete signs.", "Check boost leaks and thermostat temperature."],
    relatedModels: volkswagenModels,
    relatedPowertrains: [],
    relatedGuides: buyerGuides,
  },
  {
    slug: "volkswagen-tsi-timing-chain-belt",
    brand: "Volkswagen",
    brandHref: "/brands/volkswagen",
    system: "TSI timing chain / belt",
    title: "Volkswagen TSI Timing Chain or Belt",
    summary:
      "Volkswagen TSI timing risk depends on the exact engine generation, so buyers must identify whether the car uses a chain or belt and verify service evidence.",
    affected: ["Volkswagen TSI petrol engines across Golf, Polo, Passat, Tiguan and related models"],
    symptoms: ["Startup rattle", "Timing faults", "Rough idle", "No timing service proof"],
    faultCodes: ["P0016", "P0011", "P0340"],
    whyItFails: ["Some chain engines suffer tensioner or chain stretch issues.", "Belt engines become risky when intervals are ignored.", "Wrong oil and long intervals increase wear."],
    repairDifficulty: "Medium",
    estimatedCost: "Medium for scheduled belt service; high for chain/tensioner repair after symptoms.",
    checksBeforeBuying: ["Identify engine code and timing design.", "Ask for belt/chain invoices.", "Listen from cold start.", "Scan for cam/crank timing faults."],
    relatedModels: volkswagenModels,
    relatedPowertrains: [{ label: "VAG EA888", href: "/powertrains/vag-ea888" }],
    relatedGuides: buyerGuides,
  },
  {
    slug: "volkswagen-adblue-system",
    brand: "Volkswagen",
    brandHref: "/brands/volkswagen",
    system: "AdBlue / SCR",
    title: "Volkswagen AdBlue System",
    summary:
      "Volkswagen AdBlue faults can lead to countdown/no-start warnings, so buyers should check SCR status, NOx data, and repair history before purchase.",
    affected: ["Modern Volkswagen Euro 6 diesel models with AdBlue/SCR systems"],
    symptoms: ["AdBlue warning", "No-start countdown", "Check-engine light", "Emissions readiness failure"],
    faultCodes: ["P204F", "P20EE", "P2002"],
    whyItFails: ["NOx sensors, dosing valves, pumps, tank heaters, and software all interact.", "Short drives and weak voltage complicate diagnosis.", "Cleared codes may return after readiness runs."],
    repairDifficulty: "Medium",
    estimatedCost: "Medium to high depending on tank, pump, or sensor involvement.",
    checksBeforeBuying: ["Scan SCR/NOx modules.", "Check for countdown history.", "Verify AdBlue tank, injector, or sensor invoices.", "Drive long enough for monitors to run."],
    relatedModels: [{ label: "Volkswagen Passat", href: "/models/volkswagen-passat" }, { label: "Volkswagen Tiguan", href: "/models/volkswagen-tiguan" }],
    relatedPowertrains: [],
    relatedGuides: buyerGuides,
  },
  {
    slug: "volkswagen-turbo-wastegate",
    brand: "Volkswagen",
    brandHref: "/brands/volkswagen",
    system: "Turbo wastegate",
    title: "Volkswagen Turbo Wastegate",
    summary:
      "Turbo wastegate faults on VW TSI/TDI engines can create rattles, underboost, overboost, and poor drivability, so boost logs matter before buying.",
    affected: ["Volkswagen turbo petrol and diesel models across TSI and TDI engines"],
    symptoms: ["Wastegate rattle", "Underboost", "Overboost", "Limp mode"],
    faultCodes: ["P0299", "P0234", "P0101"],
    whyItFails: ["Heat and vibration wear actuator rods and wastegate bushings.", "Boost leaks and sensors can mimic turbo faults.", "Tuned cars increase turbo stress."],
    repairDifficulty: "Medium",
    estimatedCost: "Medium for actuator/linkage; high for turbo replacement.",
    checksBeforeBuying: ["Log requested vs actual boost.", "Inspect actuator movement and turbo noises.", "Check for tuning history.", "Scan after a full-load test drive."],
    relatedModels: volkswagenModels,
    relatedPowertrains: [{ label: "VAG EA888", href: "/powertrains/vag-ea888" }],
    relatedGuides: buyerGuides,
  },
];

export function getPartsFailureItem(slug: string, locale: Locale = "en") {
  const item = partsFailureItems.find((entry) => entry.slug === slug);
  return item ? translateValue(locale, item) : undefined;
}

export function getLocalizedPartsFailureItems(locale: Locale) {
  return translateValue(locale, partsFailureItems);
}
