import type { Locale } from "@/lib/i18n";

const copy = {
  en: {
    tools: "Engineering Tools",
    toolsIntro: "Practical tools for comparing cars, planning ownership costs, decoding faults, and choosing the right model year.",
    compare: "Vehicle Comparison",
    compareIntro: "Compare reliability scores, known risks, strengths, and inspection priorities side by side.",
    cost: "Ownership Cost Calculator",
    costIntro: "Build a realistic annual maintenance and repair reserve from vehicle, age, mileage, and history.",
    faults: "Fault-Code Library",
    faultsIntro: "Understand common OBD fault codes, likely systems, first checks, and when to stop driving.",
    years: "Model-Year Guides",
    yearsIntro: "See how one production year changes the reliability picture for a specific model.",
    openTool: "Open tool",
    firstVehicle: "First vehicle",
    secondVehicle: "Second vehicle",
    score: "Reliability score",
    risk: "Risk level",
    bestFor: "Best for",
    keyRisks: "Key risks",
    inspectFirst: "Inspect first",
    verdict: "Verdict",
    model: "Model",
    vehicleAge: "Vehicle age",
    annualDistance: "Annual distance",
    history: "Service history",
    usage: "Main use",
    good: "Complete",
    partial: "Partial",
    poor: "Unknown",
    mixed: "Mixed",
    city: "Mostly city",
    highway: "Mostly highway",
    routine: "Routine service",
    wear: "Wear items",
    reserve: "Repair reserve",
    annualEstimate: "Estimated annual ownership budget",
    monthly: "per month",
    estimateNote: "Planning estimate only. Fuel, tax, insurance, depreciation, and unexpected major failures are excluded.",
    searchCodes: "Search by code, symptom, or system",
    allSystems: "All systems",
    commonMeaning: "Common meaning",
    symptoms: "Common symptoms",
    likelyCauses: "Likely causes",
    firstChecks: "First checks",
    important: "Important",
    codeDisclaimer: "A fault code identifies a detected condition, not a failed part. Confirm manufacturer-specific subcodes and live data.",
    browseYears: "Browse model years",
    generation: "Generation",
    bestChoice: "Strongest buying angle",
    avoidIf: "Walk away or investigate deeply if",
    highlights: "Why it stands out",
    related: "Related technical pages",
    viewGuide: "View guide",
    noResults: "No matching fault codes. Try a shorter code or system name.",
  },
  nl: {
    tools: "Technische tools",
    toolsIntro: "Praktische tools om auto's te vergelijken, eigendomskosten te plannen, storingen te begrijpen en het juiste modeljaar te kiezen.",
    compare: "Voertuigen vergelijken",
    compareIntro: "Vergelijk betrouwbaarheidsscores, bekende risico's, sterke punten en inspectieprioriteiten.",
    cost: "Kostencalculator",
    costIntro: "Bereken een realistische jaarlijkse onderhouds- en reparatiereserve op basis van auto, leeftijd, kilometers en historie.",
    faults: "Storingscodebibliotheek",
    faultsIntro: "Begrijp veelvoorkomende OBD-codes, mogelijke systemen, eerste controles en wanneer doorrijden onverstandig is.",
    years: "Modeljaargidsen",
    yearsIntro: "Bekijk hoe een specifiek productiejaar het betrouwbaarheidsbeeld van een model verandert.",
    openTool: "Open tool",
    firstVehicle: "Eerste voertuig",
    secondVehicle: "Tweede voertuig",
    score: "Betrouwbaarheidsscore",
    risk: "Risiconiveau",
    bestFor: "Beste voor",
    keyRisks: "Belangrijkste risico's",
    inspectFirst: "Eerst inspecteren",
    verdict: "Conclusie",
    model: "Model",
    vehicleAge: "Leeftijd voertuig",
    annualDistance: "Kilometers per jaar",
    history: "Onderhoudshistorie",
    usage: "Hoofdgebruik",
    good: "Volledig",
    partial: "Gedeeltelijk",
    poor: "Onbekend",
    mixed: "Gemengd",
    city: "Vooral stad",
    highway: "Vooral snelweg",
    routine: "Regulier onderhoud",
    wear: "Slijtageonderdelen",
    reserve: "Reparatiereserve",
    annualEstimate: "Geschat jaarlijks eigendomsbudget",
    monthly: "per maand",
    estimateNote: "Alleen een planningsschatting. Brandstof, belasting, verzekering, afschrijving en onverwachte grote defecten zijn uitgesloten.",
    searchCodes: "Zoek op code, symptoom of systeem",
    allSystems: "Alle systemen",
    commonMeaning: "Gebruikelijke betekenis",
    symptoms: "Veelvoorkomende symptomen",
    likelyCauses: "Waarschijnlijke oorzaken",
    firstChecks: "Eerste controles",
    important: "Belangrijk",
    codeDisclaimer: "Een storingscode beschrijft een gedetecteerde toestand, niet automatisch een defect onderdeel. Controleer merkspecifieke subcodes en live data.",
    browseYears: "Bekijk modeljaren",
    generation: "Generatie",
    bestChoice: "Sterkste aankoopkeuze",
    avoidIf: "Loop weg of onderzoek grondig als",
    highlights: "Waarom dit jaar opvalt",
    related: "Gerelateerde technische pagina's",
    viewGuide: "Bekijk gids",
    noResults: "Geen overeenkomende codes. Probeer een kortere code of systeemnaam.",
  },
  ar: {
    tools: "أدوات هندسية",
    toolsIntro: "أدوات عملية لمقارنة السيارات وتخطيط تكاليف الملكية وفهم الأعطال واختيار سنة الموديل المناسبة.",
    compare: "مقارنة السيارات",
    compareIntro: "قارن درجات الاعتمادية والمخاطر المعروفة ونقاط القوة وأولويات الفحص جنباً إلى جنب.",
    cost: "حاسبة تكلفة الملكية",
    costIntro: "قدّر ميزانية سنوية واقعية للصيانة والإصلاح حسب السيارة والعمر والمسافة وسجل الصيانة.",
    faults: "مكتبة رموز الأعطال",
    faultsIntro: "افهم رموز OBD الشائعة والأنظمة المحتملة والفحوص الأولى ومتى يجب التوقف عن القيادة.",
    years: "أدلة سنوات الموديل",
    yearsIntro: "اعرف كيف تغيّر سنة إنتاج محددة صورة اعتمادية الموديل.",
    openTool: "افتح الأداة",
    firstVehicle: "السيارة الأولى",
    secondVehicle: "السيارة الثانية",
    score: "درجة الاعتمادية",
    risk: "مستوى الخطر",
    bestFor: "الأنسب لـ",
    keyRisks: "أهم المخاطر",
    inspectFirst: "افحص أولاً",
    verdict: "الخلاصة",
    model: "الموديل",
    vehicleAge: "عمر السيارة",
    annualDistance: "المسافة السنوية",
    history: "سجل الصيانة",
    usage: "الاستخدام الرئيسي",
    good: "كامل",
    partial: "جزئي",
    poor: "غير معروف",
    mixed: "مختلط",
    city: "داخل المدينة",
    highway: "طرق سريعة",
    routine: "الصيانة الدورية",
    wear: "قطع الاستهلاك",
    reserve: "احتياطي الإصلاح",
    annualEstimate: "ميزانية الملكية السنوية المقدرة",
    monthly: "شهرياً",
    estimateNote: "تقدير للتخطيط فقط. لا يشمل الوقود والضرائب والتأمين والاستهلاك والأعطال الكبرى غير المتوقعة.",
    searchCodes: "ابحث بالرمز أو العَرَض أو النظام",
    allSystems: "كل الأنظمة",
    commonMeaning: "المعنى الشائع",
    symptoms: "الأعراض الشائعة",
    likelyCauses: "الأسباب المحتملة",
    firstChecks: "الفحوص الأولى",
    important: "مهم",
    codeDisclaimer: "رمز العطل يصف حالة مكتشفة ولا يثبت تلف قطعة بعينها. تحقق من الرموز الفرعية وبيانات المصنع.",
    browseYears: "تصفح سنوات الموديل",
    generation: "الجيل",
    bestChoice: "أفضل خيار شراء",
    avoidIf: "ابتعد أو افحص بعمق إذا",
    highlights: "لماذا تتميز هذه السنة",
    related: "صفحات تقنية مرتبطة",
    viewGuide: "عرض الدليل",
    noResults: "لا توجد رموز مطابقة. جرّب رمزاً أقصر أو اسم النظام.",
  },
} as const;

export function getToolCopy(locale: Locale) {
  return copy[locale];
}
